package api.my_market_advisory_security;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class GatewaySecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {
}
